export const UPDATE_COMIC_SEARCH_FORM = 'UPDATE_COMIC_SEARCH_FORM';
export const UPDATE_TITLE_INPUT = 'UPDATE_TITLE_INPUT';
export const UPDATE_ISSUE_NUMBER_INPUT = 'UPDATE_ISSUE_NUMBER_INPUT';
export const SET_COMIC_RESULTS = 'SET_COMIC_RESULTS';
export const TOGGLE_COMIC_SEARCH_LOADING = 'TOGGLE_COMIC_SEARCH_LOADING';
