export const UPDATE_TITLE_INPUT = 'UPDATE_TITLE_INPUT';
export const UPDATE_ISSUE_NUMBER_INPUT = 'UPDATE_ISSUE_NUMBER_INPUT';
// Comics.
export const SET_COMIC_SEARCH_RESULTS = 'SET_COMIC_SEARCH_RESULTS';
export const SET_COMIC_RESULTS = 'SET_COMIC_RESULTS';
export const SET_SELECTED_COMIC_RESULT = 'SET_SELECTED_COMIC_RESULT';
export const TOGGLE_COMIC_SEARCH_LOADING = 'TOGGLE_COMIC_SEARCH_LOADING';
// Storage Containers.
export const SET_STORAGE_CONTAINERS = 'SET_STORAGE_CONTAINERS';
